// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2gzPdLIn8yUbqPbyj3FkCePP6p_1km8',
    appId: '1:736189997267:web:473ef7a669ef375d65b426',
    messagingSenderId: '736189997267',
    projectId: 'app1-98021',
    authDomain: 'app1-98021.firebaseapp.com',
    storageBucket: 'app1-98021.firebasestorage.app',
    measurementId: 'G-JB519M2RGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirP8NYcQDqEBMxiHQ1wP94dYneI7D6mI',
    appId: '1:736189997267:android:c65fbe588b0ce68965b426',
    messagingSenderId: '736189997267',
    projectId: 'app1-98021',
    storageBucket: 'app1-98021.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXbacnd3H-iwlMdSPFape5eG8RqV8zctk',
    appId: '1:736189997267:ios:47e7c6ff338282bd65b426',
    messagingSenderId: '736189997267',
    projectId: 'app1-98021',
    storageBucket: 'app1-98021.firebasestorage.app',
    iosBundleId: 'com.hieublt.app1',
  );

}